project:
  type: website
  output-dir: docs

website:
  title: "Aditya Arya"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Viz
        menu:
          - href: income-inequality.qmd
            text: Income inequality
          - href: big-tech-stock-prices.qmd
            text: Big Tech stocks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
