project:
  type: website
  output-dir: docs

website:
  title: "aarya28-tech.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: income-inequality.qmd
        text: TidyTuesday

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

